version: '3.1'

services:
  mongo1:
    container_name: mongo1
    image: mongo:4.2.20-bionic
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo1:/data/db
      - ./scripts/setup-mongo-replset.sh:/scripts/setup-mongo-replset.sh
      - ./scripts/setup-mongo-admin-user.sh:/scripts/setup-mongo-admin-user.sh
    command: mongod -replSet rs0

  ## only enable mongo-express after setting up the replset and admin user
  # mongo-express:
  #   container_name: mongo-express
  #   image: mongo-express:1.0.0-alpha.4
  #   restart: always
  #   ports:
  #     - 18081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo1:27017/admin?replicaSet=rs0
  #   depends_on:
  #     - mongo1

  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg14
    restart: always
    ports:
      - 5112:5432
    volumes:
      - ./data/timescaledb:/var/lib/postgresql/data
      - ./scripts/setup-timescaledb.sh:/scripts/setup-timescaledb.sh
      - ./scripts/setup-timescaledb-ext.sql:/scripts/setup-timescaledb-ext.sql
    environment:
      POSTGRES_DB: harness_gitops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    container_name: redis
    image: redis:7.0.0-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
      - ./scripts/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
