version: '3.1'

services:
  mongo1:
    image: mongo:4.2.20-bionic
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
      - ./scripts/setup-mongo-replset.sh:/scripts/setup-mongo-replset.sh
    command: mongod -replSet rs0

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    restart: always
    ports:
      - 5112:5432
    volumes:
      - ./data/timescaledb:/var/lib/postgresql/data
      - ./scripts/setup-timescaledb.sh:/scripts/setup-timescaledb.sh
      - ./scripts/setup-timescaledb-ext.sql:/scripts/setup-timescaledb-ext.sql
    environment:
      POSTGRES_DB: harness_gitops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7.0.0-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
      - ./scripts/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
